In [2]:
import numpy as np

In [8]:
X=np.array([[1.,2],[1,3],[-1,2]]) 
T=np.array([[2.],[5],[-2]])
N,D = X.shape
c = 1.
M = 2.
sig = 1.
lmb = 0.2
I = np.eye(N)

In [13]:
def funKernel_a(x,x_): 
    print(x, x_)
    return np.dot(x,x_)

In [10]:
Ka,Kb,Kc=np.zeros((N,N)),np.zeros((N,N)),np.zeros((N,N))
for n in range(N):
    for m in range(N):
        Ka[n,m] = funKernel_a(X[n],X[m])
Ka

array([[ 5.,  7.,  3.],
       [ 7., 10.,  5.],
       [ 3.,  5.,  5.]])

In [11]:
Ka_inv_t = np.dot(np.linalg.inv(Ka+lmb*I),T)
# a = (K+lmb*I)^-1 * t
Ka_inv_t


array([[-6.48566464],
       [ 6.23370982],
       [-2.63683753]])

In [14]:
x = np.array([0.5,1.2])
ka = np.array([funKernel_a(X[n], x) for n in range(N)])
ka

[1. 2.] [0.5 1.2]
[1. 3.] [0.5 1.2]
[-1.  2.] [0.5 1.2]


array([2.9, 4.1, 1.9])

In [16]:
ya= np.dot(ka,Ka_inv_t)
ya

array([1.73979149])